### PR TITLE
EL7 support

### PR DESCRIPTION
**Pull request by martbhell**
Hello, 

I've made this work with EL7 as well as add option to define an acl on the recv channels.
Only added the acl things on the el7 template (which wasn't looking exactly like the one you have for Ubuntu 14)

### CODE REVIEW

**Comment by badmutex** [comment]
I'll take a look this week and get back to you.
Thank for submitting this @martbhell !

**Comment by martbhell** [comment]
Sure, the nexted for loops are slightly insane and the resulting output does not look nice in gmond.conf but it works. And the indentation I used in the template file I think is necessary to be able to give a little bit of help what the loops are doing.

This kind of config:

<pre>
ganglia_tcp_accept_channels:
      - family: "inet6"
        port: "{{ ganglia_defaults_gmon_port }}"
        acl:
         - default: "deny"
           access:
            - ip: "IP:version:6:address::here"
              mask: 128
              action: "allow" 
</pre>

Results in this kind of config:

<pre>
tcp_accept_channel {
         port = 8649
                  family = inet6
                     acl {
                          default = deny
                                           access {
                                 action = allow
                       ip = IP:version:6:address::here
                       mask = 128
                                                     }
   }
     }
</pre>

**Comment by badmutex** [comment]
Looks good, thank you for the contribution.
Please do note that I will be licensing this as Apache v2.0 and adding you and the CSC into a contributors file (I'll ping you the changes when I do so).
If you are comfortable with this I'll merge this PR.

**Comment by martbhell** [comment]
Great! Sounds good to me. Are you going to make a release too?

**Comment by badmutex** [comment]
I've merged the changes into `unstable` and made some modifications (see b8aa258) so I'm closing the PR.
I'll merge into `master` and tag <del>`v2.0.0`</del> `v1.1.0` this week.

_edit_: version

**Pull request closed without merging**
